### ISSUE TITLE
txid from README is not mined

### ISSUE THREAD

**Issue by rosmcmahon** [renzholy/scar#9]
https://arweave.net/tx/KPXb-bunjcgY5uuy-vjFnwmpcsYGlP6fl84dqALqpmk/status

gives 404

another example: https://viewblock.io/arweave/tx/KPXb-bunjcgY5uuy-vjFnwmpcsYGlP6fl84dqALqpmk 
*(sorry for using another block explorer)

**Comment by rosmcmahon** [comment]
@renzholy ?

**Comment by aliez-ren** [comment]
It's not a tx id. It's bundle id

**Comment by rosmcmahon** [comment]
what bundle? it's not mined what ever it is

**Comment by rosmcmahon** [comment]
@renzholy please reopen. issue not resolved.

**Comment by rosmcmahon** [comment]
![image](https://user-images.githubusercontent.com/1430130/190949699-b6f8f722-199a-4595-9f6d-3b2a17f10350.png)
https://v2.viewblock.io/arweave/tx/KPXb-bunjcgY5uuy-vjFnwmpcsYGlP6fl84dqALqpmk
nothing found in bundle indexers

**Comment by rosmcmahon** [comment]
check your discord friend-requests

**Comment by rosmcmahon** [comment]
@renzholy ?

**Comment by aliez-ren** [comment]
maybe you can deploy to arweave using source code in this repo and then submit a pull request to change the tx id
